### ISSUE TITLE
error installing jasper report

### ISSUE THREAD

**Issue by itskaps** [saguas/jasper_erpnext_report#13]
frappe@ac:~/frappe-bench$ bench get-app jasper_erpnext_report https://github.com/saguas/jasper_erpnext_report.git
INFO:bench.app:getting app jasper_erpnext_report
INFO:bench.utils:git clone https://github.com/saguas/jasper_erpnext_report.git  --depth 1 --origin upstream
Cloning into 'jasper_erpnext_report'...
remote: Counting objects: 251, done.
remote: Compressing objects: 100% (203/203), done.
remote: Total 251 (delta 52), reused 152 (delta 34), pack-reused 0
Receiving objects: 100% (251/251), 23.71 MiB | 8.60 MiB/s, done.
Resolving deltas: 100% (52/52), done.
Checking connectivity... done.
('installing', u'jasper_erpnext_report')
INFO:bench.app:installing jasper_erpnext_report
INFO:bench.utils:./env/bin/pip install -q  -e ./apps/jasper_erpnext_report --no-cache-dir
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 13, in main
    commands = get_app_groups()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 25, in get_app_groups
    app_commands = get_app_commands(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 63, in get_app_commands

**Comment by wispmac** [comment]
I am also getting an error. Below is the complete traceback:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/wispmac/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/wispmac/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/wispmac/erpnext/env/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/wispmac/erpnext/env/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/wispmac/erpnext/env/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/wispmac/erpnext/env/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/wispmac/erpnext/env/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wispmac/erpnext/env/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/wispmac/erpnext/apps/frappe/frappe/commands/utils.py", line 24, in build
    frappe.init('')
  File "/home/wispmac/erpnext/apps/frappe/frappe/__init__.py", line 174, in init
    setup_module_map()
  File "/home/wispmac/erpnext/apps/frappe/frappe/__init__.py", line 963, in setup_module_map
    for module in get_module_list(app):
  File "/home/wispmac/erpnext/apps/frappe/frappe/__init__.py", line 837, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/wispmac/erpnext/apps/frappe/frappe/__init__.py", line 795, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/wispmac/erpnext/apps/jasper_erpnext_report/jasper_erpnext_report/__init__.py", line 23, in <module>
    from .utils.utils import get_Frappe_Version
  File "/home/wispmac/erpnext/apps/jasper_erpnext_report/jasper_erpnext_report/utils/utils.py", line 10, in <module>
    from . jasper_email import set_jasper_email_doctype
  File "/home/wispmac/erpnext/apps/jasper_erpnext_report/jasper_erpnext_report/utils/jasper_email.py", line 9, in <module>
    from jasper_erpnext_report.utils.file import get_jasper_path, write_file, get_html_reports_path
  File "/home/wispmac/erpnext/apps/jasper_erpnext_report/jasper_erpnext_report/utils/file.py", line 7, in <module>
    from frappe.utils.file_manager import get_content_hash
ImportError: No module named file_manager
