### ISSUE TITLE
Issue with bench run-tests

### ISSUE THREAD

**Issue by fderyckel** [saguas/jasper_erpnext_report#6]
Hi there,

I have tried to install the jasper report app, and I am having some issues with the pidgins.
I did bench requirements, but it seems like the pidgins is not installed properly.  

```
franky1@erpnextTesting:~$ bench update --requirements
Requirement already satisfied (use --upgrade to upgrade): Pillow in ./env/lib/python2.7/site-packages
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
________________________________________________________________________________
Bench: Open source installer + admin for Frappe and ERPNext (https://erpnext.com)

franky1@erpnextTesting:~$ bench run-tests
CLASSPATH /home/franky1/frappe-bench/apps/jasper_erpnext_report/jasper_erpnext_report/java/lib/*:.:
pyjnius is not installed: 'JAVA_HOME'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/franky1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/franky1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/commands.py", line 779, in run_tests
    ret = frappe.test_runner.main(app, module, doctype, context.verbose, tests=tests, force=context.force)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/test_runner.py", line 38, in main
    ret = run_all_tests(app, verbose)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/test_runner.py", line 73, in run_all_tests
    _add_test(path, filename, verbose, test_suite=test_suite)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/test_runner.py", line 128, in _add_test
    make_test_records(doctype, verbose)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/test_runner.py", line 145, in make_test_records
    make_test_records_for_doctype(options, verbose, force)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/test_runner.py", line 190, in make_test_records_for_doctype
    frappe.local.test_objects[doctype] += make_test_objects(doctype, test_module.test_records, verbose)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/test_runner.py", line 237, in make_test_objects
    d.insert()
  File "/home/franky1/frappe-bench/apps/frappe/frappe/model/document.py", line 188, in insert
    self.set_new_name()
  File "/home/franky1/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in set_new_name
    set_new_name(self)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/model/naming.py", line 40, in set_new_name
    frappe.throw(_("{0} is required").format(doc.meta.get_label(fieldname)))
  File "/home/franky1/frappe-bench/apps/frappe/frappe/__init__.py", line 265, in throw
    msgprint(msg, raise_exception=exc)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/__init__.py", line 258, in msgprint
    _raise_exception()
  File "/home/franky1/frappe-bench/apps/frappe/frappe/__init__.py", line 243, in _raise_exception
    raise raise_exception, encode(msg)
frappe.exceptions.ValidationError: Jasper Report Name is required
franky1@erpnextTesting:~$ 

```

How can I check if I  have JAVA_HOME exported and added it to PATH?

Thanks in advance.

**Comment by saguas** [comment]
Hi. pyjnius is not installed: 'JAVA_HOME'. Yes you need to export JAVA_HOME.

Assuming you are on linux, you need to edit .bashrc in terminal:

In terminal do nano ~/.bashrc to edit this file.

Look for JAVA_HOME in the end of the file. If it is there look if it
is some thing like this: export
JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64. Note: the path to openjdk
maybe different. If it is not there then set like my example but
change the path - see note bellow.

And to export the PATH: export
PATH=$PATH:/usr/lib/jvm/java-7-openjdk-amd64/bin. Note: The path to
openjdk maybe different.

close and save and then do in terminal source ~/.bashrc

Note: If you need to know the correct path to openjdk, start by look
in /usr/lib/jvm/java-7-[tab]. In the end [tab] is to press tab key for
linux to show you all the options.You just need the path to
java-7-openjdk but as you can see in my case has an extra work - amd64
(java-7-openjdk-amd64).

Good luck.

Luis

2016-01-30 5:52 GMT+00:00 François notifications@github.com:

**Comment by fderyckel** [comment]
Sorry it is not clear to me what I have to add to the .bashrc file
is it:

```
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export PATH=$PATH:/usr/lib/jvm/java-7-openjdk-amd64/bin
```

 or just

```
JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
PATH=$PATH:/usr/lib/jvm/java-7-openjdk-amd64/bin
```

Also what do you mean by 

> then do in terminal source ~/.bashrc

**Comment by saguas** [comment]
Hi. 
Put `export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64 and
export PATH=$PATH:/usr/lib/jvm/java-7-openjdk-amd64/bin`

After that save and while in terminal/console run `source ~/-bashrc` to reload the file and export JAVA_HOME and PATH. If you are not in terminal you do not need to source the file.
