### ISSUE TITLE
issue with bench uninstall-app

### ISSUE THREAD

**Issue by fderyckel** [saguas/jasper_erpnext_report#7]
Hi @saguas,

When trying to use bench uninstall app, I get this issue:

```
franky1@erpnextTesting:~$ bench uninstall-app jasper_erpnext_report
All doctypes (including custom), modules related to this app will be deleted. Are you sure you want to continue (y/n) ? y
Backing up...
removing Jasper PermRole...
removing JasperServerConfig...
removing Jasper Reports...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/franky1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/franky1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/commands.py", line 919, in uninstall
    remove_app(app, dry_run)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/installer.py", line 177, in remove_app
    frappe.db.sql("drop table `tab{0}`".format(doctype.name))
  File "/home/franky1/frappe-bench/apps/frappe/frappe/database.py", line 108, in sql
    self.check_transaction_status(query)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/database.py", line 206, in check_transaction_status
    raise Exception, 'This statement can cause implicit commit'
Exception: This statement can cause implicit commit

```

Any idea how I can uninstall the app?

Thanks.

**Comment by saguas** [comment]
This question is for frappe forum. I don't see any thing related with jasper here. Maybe it is a bug in uninstall.
