### ISSUE TITLE
Error While Installing jasper Report after executing bench update command

### ISSUE THREAD

**Issue by kcs-sales** [saguas/jasper_erpnext_report#9]
~/frappe-bench$ bench install-app jasper_erpnext_report
Installing jasper_erpnext_report...
Updating jasper_erpnext_report      : [========                                ]Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/erp/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/erp/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(_args, *_kwargs)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(_args, *_kwargs)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, *_kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), _args, *_kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/commands.py", line 163, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/erp/frappe-bench/apps/frappe/frappe/installer.py", line 125, in install_app
    sync_for(name, force=True, sync_everything=True, verbose=verbose)
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/sync.py", line 43, in sync_for
    import_file_by_path(doc_path, force=force)
  File "/home/erp/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 54, in import_file_by_path
    import_doc(doc, force=force, data_import=data_import, pre_process=pre_process)
  File "/home/erp/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 122, in import_doc
    doc.insert()
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 211, in insert
    self.run_post_save_methods()
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 635, in run_post_save_methods
    self.run_method("on_update")
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 579, in run_method
    return Document.hook(fn)(self, _args, *_kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 735, in composer
    return composed(self, method, _args, *_kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 718, in runner
    add_to_return_value(self, fn(self, _args, *_kwargs))
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 573, in <lambda>
    fn = lambda self, _args, *_kwargs: getattr(self, method)(_args, *_kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 135, in on_update
    self.run_module_method("on_doctype_update")
  File "/home/erp/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 144, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "/home/erp/frappe-bench/apps/frappe/frappe/modules/__init__.py", line 64, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(get_module_name(doctype, module, prefix))
  File "/home/erp/frappe-bench/apps/frappe/frappe/**init**.py", line 599, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/home/erp/frappe-bench/apps/jasper_erpnext_report/jasper_erpnext_report/jasper_erpnext_report/doctype/jasperserverconfig/jasperserverconfig.py", line 7, in <module>
    import jasper_erpnext_report.core.JasperRoot as Jr
  File "/home/erp/frappe-bench/apps/jasper_erpnext_report/jasper_erpnext_report/core/JasperRoot.py", line 11, in <module>
    import JasperServer as Js, JasperLocal as Jl, JasperBase as Jb
  File "/home/erp/frappe-bench/apps/jasper_erpnext_report/jasper_erpnext_report/core/JasperServer.py", line 30, in <module>
    import JasperBase as Jb
  File "/home/erp/frappe-bench/apps/jasper_erpnext_report/jasper_erpnext_report/core/JasperBase.py", line 14, in <module>
    _logger = frappe.logger("jasper_erpnext_report")
TypeError: 'NoneType' object is not callable

**Comment by saguas** [comment]
I can´t see why this error is occurring. Try to comment the line to see if it is because the logger. With me is everything ok, even the logger.

**Comment by kcs-sales** [comment]
Because this problem only occur , when you try to install or de-install jasper_erpnext_report after bench update . Its okay with previous release of frappe update , but  there is problems in new update , because frappe team has updated logger in new system.

**Comment by kcs-sales** [comment]
Please Fix with frappe.logger.

**Comment by saguas** [comment]
I install jasper_erpnext_report on my macbook and everything went well. I guess the problem is because you install a fresh frappe. If it is the case try to ask frappe team what is making this happening occur.
